### ISSUE TITLE
Stuff we need @33c3 ?

### ISSUE THREAD

**Issue by iwess** [iwess/33c3-Science-Hack-and-Communication-Assembley-#7]
List it - organize yourself , please.

**Comment by LeLamp** [comment]
Are we going for a fixed assembly?
I would like to really do the Laser-LuMa as an easy to spot sign, maybe reading "Science - Hack and Com"? I would bring about 10 Lasers and some diodes for illuminating the thing - anyone got an appealing transparent blow-up thingi to contribute? (no one things that's silly, right?)

**Comment by SimonWaldherr** [comment]
I could also bring a handful of LASERs (40-50) and a RGB-LED-Matrix with 8192 LEDs

**Comment by iwess** [comment]
@LeLamp 
Ja, die Bewerbung beim 33c3 ist auf einen fixen Platz, Public.
Brauchen wir da speziell mehr Platz oder aus Sicherheitsgründen etwas, das müssten wir dann noch mit im Wiki angeben

@LeLamp @SimonWaldherr 
Vielleicht sollten wir, statt uns zu den Podcastern zu gesellen, doch lieber unten im Makerspace die Nähe der anderen Science - Maker - Assemblies suchen - also uns dahin verclustern ;) 
Wenn niemand widerspricht, dann trag ich das mal als Priorität 1 in unserer Orts-Wunschliste im Assembly-Proposal ein?

**Comment by iwess** [comment]
Ich baue auch noch was transparent - blinky - in die Höhe schwebend artiges oder so ...  ;)

**Comment by LeLamp** [comment]
@iwess 
ich frag jetzt mal ganz provokant... sind wir mit sci comm denn näher an den maker assemblies, seh ich eigentlich nicht so...

**Comment by iwess** [comment]
@LeLamp 
Och, dann antworte ich ganz provokant ... Hast wohl noch nicht die Assembleyliste durchgelesen, wer da noch sci, make, lab, engagment things macht? Ich find da ja einige sehr spannend ;) - Guck mal im 33c3 Wiki - da kommt ne ganze Mikroskopiermanschaft #LoL

PS: Wir müssen aber och nicht - Können sie uns ja auch einladen oder selbst vorbei schauen. Wir werden eh hingesetzt, wo Platz ist, wenn überhaupt.

**Comment by Mincolas** [comment]
Hängt wahrscheinlich auch etwas davon ab was wir am Tisch machen wollen. Wenn wir selbst im wesentlichen Basteln wollen, ist die Nähe zu den anderen "Makern" sicher interessant. Wenn es uns um Gespräche und Diskussionen geht, dann wäre sicher eine ruhigere Ecke auch überlegenswert.
Ich finde Gespräche in wuseligen Umgebungen echt anstrengend. 

Wenn wir allerdings "Laufkundschaft" erreichen wollen, dann ist die wuselige Ecke wieder besser...
